### PR TITLE
33 betweenness calculations

### PR DESCRIPTION
**Pull request by TheoBerglin**

### CODE REVIEW

**Comment by giovannivolpe** [comment]
I think we can wait to merge this until we take care of the negative weights, as we discussed today

**Comment by TheoBerglin** [comment]
I don't really see how betweenness_in/out would work as a measure? 
I agree that we can wait on merging this until we have a working method for negative weights

**Comment by giovannivolpe** [comment]
Ok, let's wait to merge until we have the negative weights implemented.

**Comment by giovannivolpe** [comment]
Not completely sure about how to implement betweenness_in/out, or it it's even necessary. Probably not.
Mite, can you weight in?

**Comment by mitemijalkov** [comment]
I checked the original papers of the betweenness and the measure calculations seem to be just consisting of two steps: first, the shortest path length between all pairs of edges are calculated and then the betweenness centrality is decided based on dependence measure (as proposed by Brandes, 2001). Therefore, since we decided on not to go forward and include negative weights in the path length calculation, it follows that we do not need to do the negative weights for the betweenness. 
The measure can be extended for directed graphs and actually the codes provided in the brain connectivity toolbox claim that the input matrix can be undirected or directed anyway. Therefore, I think that that might be actually useful (although, when community detection algorithm are discussed based on this measure, the suggestion is that the undirected version performs very well and it is preferred for that aim.

**Comment by mitemijalkov** [comment]
I think that we can improve two things regarding the betweenness: as far as I remember we calculate only edge betweeness currently, we could include node betweenness also. Secondly, since the shortest path lengths are already calculated separately, this means that when we calculate betweenness we do a double work and recalculating everything. Maybe we should alter the code so that once path length is calculated we do not recalculate it again?

**Comment by TheoBerglin** [comment]
What is the difference between edge and node betweenness? 

As for the second suggestion I agree, this would limit the calculations which is nice not only in regards of performance but also in possible bugs or new improvements as we would only have to change one file and not two. But it would also add a problem. In the code for betweenness we use both the shortest path length and the number of paths that are the shortest path, NSP. NSP would need to be calculated in path length and returned as a output value. The idea we have discussed is to only return one value from each function and input the same two variables, adjacency matrix and type, so that we can remove the switch statement in get_measure(). We could make an exception for path length (and other heavy calculations) so it returns multiple values and another exception for betweenness so that the number of input variables is three instead of two.

**Comment by mitemijalkov** [comment]
There is a slight difference between the two in essentially in the counting of the shortest paths an edge or node participates in. However, I misspoke, and we currently calculate node betweenness. I am not sure how to implement/show the edge one so probably it is not worth doing it anyway.

For the second idea, one possibility would be to pass either adjacency or distance matrix in the function. Then depending on the input argument we can calculate the missing things inside of the function. This should not disrupt the output in all functions but maybe shorten the calculation time if distance matrix is passed instead of adjacency one.

**Pull request merged**
