### PR TITLE
36 transitivity calculations

### PR DESCRIPTION
**Pull request by TheoBerglin**

### CODE REVIEW

**Comment by TheoBerglin** [comment]
Negative weighted
How do we handle this?

My idea is to handle it similarly to positive weighted. If one of the two connections is negative we have a negative triplet. If both of the triplets are negative or positive we have a positive triplet

**Comment by mitemijalkov** [comment]
Seems logical. Do you then sum up all the triplets in the network such that the negative and positive triplets cancel with each other?

**Comment by TheoBerglin** [comment]
Yes exactly

**Comment by TheoBerglin** [comment]
@mitemijalkov have approved the changes when we talked on skype yesterday

**Comment by mitemijalkov** [comment]
Exactly, the transitivity should work correctly with that code.

**Pull request merged**
